### PR TITLE
Re-add Pokémon CP

### PR DESCRIPTION
**Pull request by ghost**
4cee7e1 accidentally removed Pokémon CP stat listing so we add it back in.

### CODE REVIEW

**Comment by Reaver01** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/136/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by RolfKoenders** [comment]
Woops my bad! Sorry :sweat_smile:

**Comment by kazyka** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/136/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by ghost** [comment]
Oops. Could someone quickly push a change that adds a space after the `</b>`?

**Comment by ghost** [comment]
@Reaver01 @kazyka

**Pull request merged**
