### PR TITLE
Update new web view

### PR DESCRIPTION
**Pull request by sniok**
image
Update new web view with:
- Simple multiple bot support
- Clean and compact view
- Scrollable bot list
- Compact view of pokemons
- IV display of pokemons
- Pokemons are sorted by CP
- Compact view of inventory
- Code clean up

### CODE REVIEW

**Comment by glenncampioni** [comment]
Looks better than what I had cooked up, I'll add my sorting logic to your code when it's accepted.

**Comment by meyer9** [comment]
:-1: Clicking the button again should close the modal.

[Rejected with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/9/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by sniok** [comment]
@jmeyer2k It was behaving wierd with multiple bots so I replaced it with close button on content window. Previous behaviour can be returned in following commits once I or someone else figure out how to do it

**Comment by Reaver01** [comment]
I will look into modifying this to work as intended

**Comment by sniok** [comment]
Opening window on button and closing on big X is a normal behavior and should not be treated like bug.

**Comment by glenncampioni** [comment]
Using the X to close works for now, so I'd say approve this so we can improve it :)

**Comment by meyer9** [comment]
:+1: gets my approval. last approval should be reaver.

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/9/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by Reaver01** [comment]
It apparently didn't take the commits I just made

**Comment by MaxLeiter** [comment]
You have to push them to his fork (as in, make a PR) @Reaver01

**Pull request closed without merging**
