### PR TITLE
Refactor main.js into modules

### PR DESCRIPTION
**Pull request by wchill**
Since `main.js` is so massive, I've tried to refactor it into more files.

It makes use of ES6 classes for holding and manipulating data and Promises (thanks to Bluebird.js) to clean up the code.

Some redundant code was also removed.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by julienlavergne** [comment]
In Pokedex.js, I had to change `entry['id'] = entryData.pokedex_entry_number;` to `entry['id'] = entryData.pokemon_id;`. Not sure though if it is a problem of the bot or the js.

Beside that, IV sort is not working in Pokemon list.

**Comment by wchill** [comment]
@Anakin5 please link me to the commit of the bot that you are using.

**Comment by julienlavergne** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev

**Comment by BobbyWibowo** [comment]
Tested 78be9e80cf636c531e044c97671a0dcc2892e93d. I had to edit a few bits, such as the one @Anakin5 said. I also had to remove WebSockets implementation because I was using PokemonGo-Bot. But other than that, it seems to be working just fine.

**EDIT:** I seem to have some issues with multi users though.
**EDIT2:** Never mind, fixed in my personal build.

**Comment by BobbyWibowo** [comment]
Shouldn't getSortedPokemon function be within Pokemon class instead of Player?

**Comment by wchill** [comment]
@BobbyWibowo maybe. I set it up that way because the `Pokemon` class is for individual Pokemon only. I can look into making it a static method.

**Comment by BobbyWibowo** [comment]
@wchill Alrighty, sounds fair enough.

**Comment by wchill** [comment]
Needs major rebasing. Closing for now.

**Pull request closed without merging**
