### PR TITLE
Show current and max hp with health bar

### PR DESCRIPTION
**Pull request by RolfKoenders**
Hello, 
Its my first PR to this project and i tried to implement feature request: #107

It looks like:
HP Bar

Styling could maybe be improved but it looks fine 😄 

Let me know what u guys think!

### CODE REVIEW

**Comment by Jasperrr91** [comment]
Looking good, styling could indeed be improved but so far so good.

**Comment by Jasperrr91** [comment]
image

**Comment by Jasperrr91** [comment]
image

**Comment by wchill** [comment]
Those images look strange due to the lack of transparency.

**Comment by RolfKoenders** [comment]
@wchill You mean the images from @Jasperrr91? i think he's trying to show how it could be improved.

**Comment by BobbyWibowo** [comment]
Unexpected identifier in line 588 of main.js. Should be:
`'HP: ' + pkmnHP + ' / ' + pkmnMHP +`
instead of the current:
`'HP: ' + pkmnHP + ' / ' pkmnMHP +`

**Comment by RolfKoenders** [comment]
@BobbyWibowo You are right. Fixed :)

**Comment by BobbyWibowo** [comment]
Working good on my installation. Thanks ;)

**Comment by BobbyWibowo** [comment]
By the way, pokemon name is missing here. Doesn't seem to be rendered in the main.js file as well. Was that intentional?

**EDIT:** Never mind. My mistake, missed 1 line in my copies.

**Comment by wchill** [comment]
I'm on mobile, can I see a render?

**Comment by wchill** [comment]
Of the latest commit, I should me tion

**Comment by RolfKoenders** [comment]
~~@BobbyWibowo The pokemon name is rendered here?~~

@wchill Would be nice to see if @BobbyWibowo can provide a screenshot.

**Comment by BobbyWibowo** [comment]
@RolfKoenders Yeah. My mistake. I missed 1 line when manually merging the change, lol..

@wchill Here's the preview on my desktop:
render

**Comment by RolfKoenders** [comment]
@BobbyWibowo You're styling looks different than i had/have :hushed:

**Comment by BobbyWibowo** [comment]
@RolfKoenders Difference in stamina bar length is most likely caused by the fact that I viewed them on a 1080p screen. Other than that, I don't see any other differences with your first picture (other than spacing in A/D/S info) :hushed:

**Comment by BobbyWibowo** [comment]
@RolfKoenders Why not use _margin: 0.3rem auto;_ for _.pkmn-progress_ in the CSS? It guarantees that the bar is centered (regardless of the container's rendered width).
squirtle

**Comment by wchill** [comment]
Yes, stamina bars definitely need some work. Also I'd set the max width of the bars to be up to the width of the images (120px, I think?)

**Comment by BobbyWibowo** [comment]
@wchill The width of the pokemon images is 120px, but limited by default to 96px by the CSS. Here's the preview of the bar with 96px max-width:
squirtle_2

**Comment by Jasperrr91** [comment]
@wchill not sure how the images are being rendered for you and where you're missing transparency but it's just a quick mock up of a possible style.

I think it's getting way too cluttered otherwise. A lot of clutter can be removed by hiding the words 'Candy' 'IV' A/D/S' and possibly CP

**Comment by Jasperrr91** [comment]
@RolfKoenders seems like the bar isn't completely in line with the text. Probably some padding somewhere?

image

**Comment by BobbyWibowo** [comment]
@Jasperrr91 The extra 'spacing' appears to be caused by these lines:
`.container .row {`
`margin-left: -0.75rem;`
`margin-right: -0.75rem;`
`}`
in materialize.min.css. Setting them back to _auto_ removes the spacing issue.

**Comment by RolfKoenders** [comment]
Alright! Just got home! Will take a look at the feedback!
What shall we do? 
- Shall i remove the visual health bar for now so we have at least the hp in text (HP: 120/170)
- Make some changes and fix the visual bar :smile:

EDIT:
I had to do some coding before going to bed. Here is what i have now. Made the height a bit smaller and made sure its centered. I also really liked the 96px width as @BobbyWibowo showed.

Current state after my next commit:

health bar

**Comment by BobbyWibowo** [comment]
Here is my latest edit. I won't make any pull request since my local copies are heavily modified here and there, and I only merged changes that I actually needed from the pull requests, so yeah, it's a pain just thinking about it (also, I'm using PokemonGoF instead of OpenPoGoBot, so my main.js doesn't have the whole websocket thingy). Anyway if you like any of the ideas from my screenshot, feel free to implement it :wink: 
pokego-bot-pokemon-list
Hint about the blue glow: I read somewhere that the blue glows in the PokeGO app means that the Pokemon was captured since 24 hours ago or less. So yeah. I thought, might as well.

**Comment by Jasperrr91** [comment]
Very nice @BobbyWibowo, can you post the modified HTML/CSS?

**Comment by RolfKoenders** [comment]
@BobbyWibowo Looks good! I will take a look and make some similar changes!. I like the bold text! (hp, cp etc..).

**Comment by BobbyWibowo** [comment]
@Jasperrr91 @RolfKoenders  Here are the pastebins of the whole main.js and main.css file. You'll have to salvage whichever parts you want by yourself, if you want, lol
main.js: http://pastebin.com/Ws3G6zw1 (uses [Moment.js](http://momentjs.com/) for the relative time display)
main.css: http://pastebin.com/gi5vneVa (custom changes were only done at the bottom of the css)
Psst. it also includes fix for experience progress bar: https://github.com/OpenPoGo/OpenPoGoWeb/issues/83#issuecomment-236033478

**UPDATE:** Here's the git repo of my version: https://github.com/BobbyWibowo/OpenPoGoWeb. I had integrated all my changes to wchill/refactor branch.

**Comment by Reaver01** [comment]
It looks like you guys are still working on this.  Let me know when it should be approved and merged.

**Comment by RolfKoenders** [comment]
@Reaver01 I will look at the changes @BobbyWibowo made, there are some nice changes. I will try to make a final commit with this which we can improve on. Then at least we have a decent version. Later on improvements can be made. Will look at this in a few hours, will be ready tonight! @Reaver01 
@BobbyWibowo Appreciate the work man!

**Comment by Reaver01** [comment]
@RolfKoenders sounds good.  also keep in mind the wchill/refactor branch as that branch is making a lot of changes and is what we are looking at for long term.  Maybe see if you can write this to stick into that branch as well.

**Comment by RolfKoenders** [comment]
@Reaver01 Cool, wasn't aware. Will take that into account!

**Comment by RolfKoenders** [comment]
@BobbyWibowo I took the changes u made for the healthbar and the stats. (Bold text, blue iv text). I think the other changes like 'time ago' can be a separate PR. 

@Reaver01 Let me know if u like it in this way!

**Comment by Reaver01** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/109/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by BobbyWibowo** [comment]
My latest edit shows the HP text within the HP bar now. I had also made capture time to only appear while sorting by time. Making it much cleaner, imho.
pokego-bot-pokemon-list_3
If you're interested to see all the changes, I've forked the repo and commited all my changes there: https://github.com/BobbyWibowo/OpenPoGoWeb. FYI, I made the changes on wchill/refactor branch. Also, due to the fact that it's quite heavily modified, I'm not gonna do any PR. So yeah, as always, feel free to salvage whatever you need.

**Comment by MaxLeiter** [comment]
:+1: thanks!

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/109/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
