### PR TITLE
Fix code formatting

### PR DESCRIPTION
**Pull request by tehp**

### CODE REVIEW

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/72/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/72/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by MaxLeiter** [comment]
Please resolve conflicts

**Comment by MaxLeiter** [comment]
poke, @tehp?

**Comment by kazyka** [comment]
Fixed - in master readme

**Pull request closed without merging**
