### PR TITLE
datails info abou gym

### PR DESCRIPTION
**Pull request by nowak-mateusz**
dispaly details info about members in gym.
usefull after PR https://github.com/PokemonGoF/PokemonGo-Bot/pull/852.

### CODE REVIEW

**Comment by Reaver01** [comment]
Please wait until the refactor. and don't submit to master. Submit to refractor branch.

**Comment by Reaver01** [comment]
Give it like 20 minutes, and then re pull and put your changes back in.

**Comment by Reaver01** [comment]
as long as @particle6 's PR is merged

**Comment by nowak-mateusz** [comment]
sorry my bad

**Pull request closed without merging**
