### PR TITLE
Egg Incubation + Gym Levels

### PR DESCRIPTION
**Pull request by jadbalout**
We still didn't add egg incubation, so.. here it is!
This commit adds the ability to monitor the egg incubation(kms left to walk from (x)km egg) while using the egg inside blue incubator(limited use incubator) or egg inside orange incubator.
This also changes /image/pokemon/Egg.png since the Egg.png is also located in the /items/ directory and would be more logical to use /items/. Thus, I also deleted the Egg.png in /pokemon/

### CODE REVIEW

**Comment by jadbalout** [comment]
This is how it looks http://prnt.sc/bzh8p4

**Comment by MaxLeiter** [comment]
Looks good to me, thanks!

:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/133/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by jadbalout** [comment]
New fix for unlimited egg incubators, apparently it's differently formatted than the limited?

**Comment by jadbalout** [comment]
Added Gym levels to the commit. Waiting for approval guys.

**Comment by jtdroste** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/133/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
