### PR TITLE
Change the forts icons and favicon

### PR DESCRIPTION
**Pull request by crusardri**
I made a new sets of forts icons and a new favicon in PNG (16x16, 32x32, 64x64 and 128x128)

### CODE REVIEW

**Comment by BobbyWibowo** [comment]
Hey man. Nice icons. Did you make them by yourselves? I was wondering if you can get an HD icon for candies. It doesn't have to be all candies. 1 type of candy will do.

**Comment by crusardri** [comment]
@BobbyWibowo yes, i made all icons.
I will try to make icons for candies later.

**Comment by crusardri** [comment]
@BobbyWibowo 
pogocandy
This?

**Comment by BobbyWibowo** [comment]
@crusardri Thanks! Looks great (imho)
pokego-bot-pokemon-list_2
-- edit: completely unrelated, but I just noticed that 'undefined' hp

**Comment by DanielVolz** [comment]
@BobbyWibowo Wow i like your map very much... I'm using it also now! Thanks! 👍

**Comment by Nihisil** [comment]
👍

**Comment by Reaver01** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/121/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by MaxLeiter** [comment]
Looks great!

:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/121/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
