### PR TITLE
Truncate Bot Name

### PR DESCRIPTION
**Pull request by RedSparr0w**
Truncate Bot names when too long

Before:

After:

### CODE REVIEW

**Comment by MaxLeiter** [comment]
You're CSS is using tabs while the rest is using spaces; please make it uniform (although in the future we may switch to all tabs)

**Comment by MaxLeiter** [comment]
:+1: from me, thanks!

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/22/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by RedSparr0w** [comment]
A majority of it was using tabs > spaces

have updated to all be tabs.

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/22/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
