### PR TITLE
Pr/9

### PR DESCRIPTION
**Pull request by Reaver01**
Add flag for menus  

Update new web view  

Improve code readability  

main.js  
- Added: openFlag variable  
- Added: logic to intelligently close/open the menus from the other
  buttons  
- Added: multibot menu will close the open menu when hiding menu or
  switching bots

### CODE REVIEW

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by wchill** [comment]
:+1:

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by wchill** [comment]
👍

**Comment by jtdroste** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
