### PR TITLE
Update 3

### PR DESCRIPTION
**Pull request by Reaver01**
main.css
- Added: class for small images
  main.js
- Changed: stats array is built by function
- Changed: run addInventory() instead of looping through buildMenu()
- Added: function to create arrays based on username
- Changed: invSuccess needs to use the user_index for multibot to work
- Changed: Menus now have tabs for each bot running
- Added: More stats to be displayed in pokemon menu: CP, Moves,  IVs
  Pokeball used

### CODE REVIEW

**Comment by Reaver01** [comment]
Approved

**Comment by Reaver01** [comment]
👍

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/5/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/5/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
