### PR TITLE
Fixed Porygon candy value not displaying correctly.

### PR DESCRIPTION
**Pull request by Dave-Walsh**
Porygon had the wrong family_id in the /data/pokemoncandy.json
This caused its candy count to display as undefined.

### CODE REVIEW

**Comment by BobbyWibowo** [comment]
That explains. I noticed this a few days ago, but after inspecting the pokemoncandy.json file, I honestly had no idea what were all those IDs mean.. lol
Thanks btw! :+1:

**Comment by jadbalout** [comment]
Nice work, thanks

**Comment by Reaver01** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/173/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by prusswan** [comment]
Why hasn't this been merged yet? Is this project still active?

**Comment by Reaver01** [comment]
As stated in the readme, this project is deprecated and will no longer be supported.

**Pull request closed without merging**
