### PR TITLE
Update 2

### PR DESCRIPTION
**Pull request by Reaver01**
index.html
- Added Google Icon Font
- Added menu buttons to menus
- Removed old maps script
  main.css
- Added CSS classes for new items
  main.js
- Added logic for imageType toggle
- Added toggle functions for new buttons

### CODE REVIEW

**Comment by meyer9** [comment]
:+1:

**Comment by jtdroste** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by jtdroste** [comment]
Please don't merge unless you're @Reaver01 

We're making sure permissions is working

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by jtdroste** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
