### PR TITLE
Added personal zoom setting

### PR DESCRIPTION
**Pull request by BoGnY**
Added option zoom in userdata.js for set personal zoom setting

### CODE REVIEW

**Comment by meyer9** [comment]
zoom setting should not be capitalized.

**Comment by BoGnY** [comment]
added new commit with your indications ;)

**Comment by MaxLeiter** [comment]
:+1: reminder to whoever merges this to squash please

Thanks! 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/91/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/91/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
