### PR TITLE
fixing the candy count

### PR DESCRIPTION
**Pull request by fierysolid**
The API response appears to have changed. Changing the web code to match the response.

### CODE REVIEW

**Comment by douglascamata** [comment]
@Reaver01 please check this, candy count is broken on current `master` branch with updated `pgoapi`.

**Comment by Reaver01** [comment]
👍

**Comment by fierysolid** [comment]
We ever going to merge this?

**Comment by Reaver01** [comment]
:+1: I hope so

**Comment by Reaver01** [comment]
@OpenPoGo/admin

**Comment by MaxLeiter** [comment]
This code is impossible to review with such a large diff... Please fix your commits so it's readable (i.e. only change code you need to change)

**Comment by xorinzor** [comment]
It seems most of the diff is just because of a change in the spaces/tabs of the code for readability

**Comment by MaxLeiter** [comment]
Then that belongs in it's own PR (we -really- need to discuss a set style at some point).

**Comment by BobbyWibowo** [comment]
The fact that it also includes WebSocket removal should make it belong to another PR imo

**Comment by xorinzor** [comment]
Sounds fair to me

**Comment by fierysolid** [comment]
Shit forgot I had a PR on this branch. The socket stuff isn't supposed to be in it

**Comment by theebanka** [comment]
So was this ever merged? Or is there some way to fix this relatively easily?

**Comment by fierysolid** [comment]
Change Pokemon_family to candy

**Comment by theebanka** [comment]
Thank you!

**Pull request closed without merging**
