### PR TITLE
Added context menu with ability to copy location

### PR DESCRIPTION
**Pull request by aslafy-z**
With a little rework on js/css imports

image

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Looks fine to me; I don't know how I feel about the console.log but that's minimal
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/145/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Comment by Reaver01** [comment]
please fix conflicts

**Comment by aslafy-z** [comment]
Done ;)

**Comment by Reaver01** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoWeb/pull-request/145/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoWeb)

**Pull request merged**
